### PR TITLE
Added placeholderColor attribute to allow custom color for placeholderText

### PR DESCRIPTION
**Pull request by dbgrandi**
It still defaults to [UIColor lightGrayColor] in the initializer.

Also, updated the Xcode project file, which set the compiler to clang instead of gcc.

### CODE REVIEW

**Comment by gcamp** [comment]
Good addition, but you seem to be using redColor as the default, not lightGrayColor.

**Comment by dbgrandi** [comment]
The red is only in the demo view controller to show overriding the default.

**Comment by gcamp** [comment]
Ha! Sorry about that.

**Comment by dbgrandi** [comment]
No worries. Thanks, @gcamp!

**Pull request merged**
