### PR TITLE
Enabling ARC.

### PR DESCRIPTION
**Pull request by joybro**
to use this textview in the projects  which also based on ARC.

### CODE REVIEW

**Comment by gcamp** [comment]
Is there a reason of doing that instead of using `-fno-objc-arc`?

**Comment by joybro** [comment]
I believe most of the recent projects enable ARC so this way would be less bothersome.

**Comment by cconstable** [comment]
Agree. I use joybro's branch for this reason.

**Comment by psineur** [comment]
I use this lib from cocoapods in ARC project, which does -fno-objc-arc automatically for you.
No problems with ARC vs. non-ARC in my case

**Comment by gcamp** [comment]
master branch is now on ARC!

**Pull request closed without merging**
